# Generated by Django 5.1.4 on 2025-09-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milktea', '0004_add_customer_order'),
        ('milktea', '0004_customer_alter_review_options_remove_category_image_and_more'),
    ]

    operations = [
    ]
